## Lab 10: SQL Python

In this lab we will look at how to use the python library pymysql to interact with MySQL Workbench.

* We will look at how to load the contents of a .csv as a pandas dataframe, preprocess it, and populate a SQL database table with this data.
* Finally, we will see how to run queries against an existing database table using pymysql.

### Part 1: European Countries Dataset

The dataset relates to countries in Europe. It contains information such as country name, its surface area, population, GDP, its capital city, and the population of its capital city.

The goal of this project is to perform Extract Load & Transform (ELT) the dataset. We will use preprocessing to ensure the data is free of any formatting errors, and store it into a SQL database.

In [ ]:
# Install any missing packages
#!pip install pymysql

In [4]:
#Load the required libraries
import pandas as pd
import numpy as np
import os
import pymysql

### 1. Extract (Gather the Data)

In [5]:
raw_csv_data = pd.read_csv('euro_countries.csv')

In [6]:
#make a dataframe to copy the data
df = raw_csv_data.copy()

In [7]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [8]:
display(df)

,Country,Area (miles2),Capital,Population,GDP (2016),Capital Population,Longitude,Longitude Direction,Latitude
0,'Albania',11099.66,'Tirana',2854710,1.186387e+10,49300,19.816667,'E',41.316667
1,'Andorra',180.70,'Andorra_la_Vella',79034,2.858518e+09,22256,1.516667,'E',42.500000
2,'Armenia',11483.83,'Yerevan',2790974,1.057230e+10,1100000,44.500000,'E',40.166667
3,'Austria',32385.46,'Vienna',8922082,3.910000e+11,1900000,16.366667,'E',48.200000
4,'Azerbaijan',2687.27,'Baku',10312992,3.784772e+10,2240000,49.866667,'E',40.383333
5,'Belarus',80154.78,'Minsk',9578167,4.740722e+10,2000000,27.566667,'E',53.900000
6,'Belgium',11786.92,'Brussels',11611419,4.680000e+11,180000,4.333333,'E',50.833333
7,'Bosnia and Herzegovina',19771.90,'Sarajevo',3270943,1.691028e+10,280000,18.416667,'E',43.866667
8,'Bulgaria',42614.85,'Sofia',6885868,5.323788e+10,1280000,23.316667,'E',42.683333
9,'Croatia',21851.06,'Zagreb',4060135,5.071496e+10,900000,16.000000,'E',45.800000
10,'Cyprus',3571.83,'Nicosia',1244188,2.004701e+10,200000,33.366667,'E',35.166667
11,'Czech Republic',30452.25,'Prague',10510751,1.950000e+11,1360000,14.466667,'E',50.083333
12,'Denmark',16581.92,'Copenhagen',5854240,3.070000e+11,795000,12.583333,'E',55.666667
13,'Estonia',17528.64,'Tallinn',1328701,2.333791e+10,438000,24.716667,'E',59.433333
14,'Faroe Islands',537.84,'Torshavn',52889,2.813000e+09,14000,6.766667,'W',62.000000
15,'Finland',130071.59,'Helsinki',5535992,2.390000e+11,657000,24.933333,'E',60.166667
16,'France',210016.71,'Paris',64531444,2.470000e+12,2100000,2.333333,'E',48.866667
17,'Georgia',1173.75,'Tbilisi',3757980,1.437802e+10,1110000,44.833333,'E',41.683333
18,'Germany',138062.74,'Berlin',83408554,3.480000e+12,3800000,13.400000,'E',52.516667
19,'Greece',50948.86,'Athens',10445365,1.930000e+11,670000,23.733333,'E',37.983333
20,'Hungary',35917.14,'Budapest',9709786,1.260000e+11,1750000,19.083333,'E',47.500000
21,'Iceland',39768.51,'Reykjavik',370335,2.004741e+10,131000,21.950000,'W',64.150000
22,'Ireland',26959.57,'Dublin',4986526,3.050000e+11,600000,6.233333,'W',53.316667
23,'Italy',116586.59,'Rome',59240329,1.860000e+12,2860000,12.483333,'E',41.900000
24,'Kosovo',4212.37,'Pristina',1662009,6.649889e+09,150000,21.166667,'E',42.666667
25,'Latvia',24939.87,'Riga',1873919,2.757270e+10,628000,24.100000,'E',56.950000
26,'Liechtenstein',61.78,'Vaduz',39039,6.237000e+09,6000,9.516667,'E',47.133333
27,'Lithuania',25207.06,'Vilnius',2786651,4.273888e+10,588000,25.316667,'E',54.683333
28,'Luxembourg',998.46,'Luxembourg',639321,5.863132e+10,123000,6.116667,'E',49.600000
29,'Malta',121.62,'Valetta',526748,1.099905e+10,6000,14.500000,'E',35.883333
30,'Moldova',13068.39,'Chisinau',3061506,6.749516e+09,535000,28.850000,'E',47.000000
31,'Monaco',0.77,'Monaco',36686,6.473000e+09,40000,7.416667,'E',43.733333
32,'Montenegro',5362.18,'Podgorica',627859,4.374127e+09,156000,19.266667,'E',42.433333
33,'Netherlands',16039.84,'Amsterdam',17501696,7.770000e+11,875000,4.916667,'E',52.350000
34,'North Macedonia',9927.84,'Skopje',2103330,1.067000e+10,547000,21.433333,'E',42.000000
35,'Norway',125009.02,'Oslo',5403021,3.710000e+11,700000,10.750000,'E',59.916667
36,'Poland',120725.99,'Warsaw',38307726,4.710000e+11,1800000,21.000000,'E',52.250000
37,'Portugal',35297.83,'Lisbon',10290103,2.050000e+11,505000,9.133333,'W',38.716667
38,'Romania',92007.33,'Bucharest',19328560,1.880000e+11,2150000,26.100000,'E',44.433333
39,'Russia',1526087.46,'Moscow',146447424,1.280000e+12,12400000,37.600000,'E',55.750000
40,'Serbia',29957.27,'Belgrade',7296769,3.829985e+10,1700000,20.500000,'E',44.833333
41,'Slovakia',18932.51,'Bratislava',5447622,8.995000e+10,660000,17.116667,'E',48.150000
42,'Slovenia',7827.45,'Ljubljana',2119410,4.470860e+10,300000,14.516667,'E',46.050000
43,'Spain',192466.06,'Madrid',47486935,1.240000e+12,3300000,3.683333,'W',40.400000
44,'Sweden',169334.30,'Stockholm',10467097,5.140000e+11,1500000,18.050000,'E',59.333333
45,'Switzerland',15942.54,'Bern',8691406,6.690000e+11,150000,7.466667,'E',46.916667
46,'Turkey',9172.63,'Ankara',84775404,8.640000e+11,1500000,32.866667,'E',39.933333
47,'Ukraine',233031.48,'Kiev',43531422,9.327048e+10,3000000,30.516667,'E',50.433333
48,'United Kingdom',94354.06,'London',67281039,2.650000e+12,9000000,0.083333,'W',51.500000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              49 non-null     object
 1   Area (miles2)        49 non-null     float64
 2   Capital              49 non-null     object
 3   Population           49 non-null     int64
 4   GDP (2016)           49 non-null     float64
 5   Capital Population   49 non-null     int64
 6   Longitude            49 non-null     float64
 7   Longitude Direction  49 non-null     object
 8   Latitude             49 non-null     float64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.6+ KB

### 2. Transform (Preprocess the Data)

#### 2.1 Convert the Area from squared miles in squared kilometres

We need to convert the Area from squared miles to squared kilometres.

In [10]:
df['Area (miles2)'] = df['Area (miles2)'] * 2.58999

Now, let's rename the column from Area (miles2) to Area (km2).

In [11]:
df = df.rename(columns={"Area (miles2)": "Area (km2)"})

#### 2.2 Reformat the Longitude to have "-" for locations West of Greenwich

We have a small issue with the values in the "Longitude" column. They should have a "-" for locations west of Greenwich (meridian line) and a blank (positive) for locations to the east of it. There is a second column called "Longitude Direction" which contains "W" or "E" depending on the direction w.r.t to the Greenwich line. We can use this information to modify the data in the "Longitude" column.

In [12]:
print(df['Longitude Direction'][0])

'E'

In [13]:
# If the longitude direction is West of Greenwich then multiply the values in the Longitude Column by -1
for i in range(len(df)):
    if df['Longitude Direction'][i] == "'W'":
        df['Longitude'][i] = df['Longitude'][i] * -1.00

C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Longitude'][i] = df['Longitude'][i] * -1.00
C:\Users\RoksolanaKryvulia-ST\AppData\Local\Temp\ipykernel_15572\2905045340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Longitude'][i] = df['Longitude'][i] * -1.00

In [14]:
# Finally delete (drop) the column called 'Longitude Direction'
df = df.drop(columns=['Longitude Direction'])

#### 2.3 Review the Transformed Data

In [15]:
display(df)

,Country,Area (km2),Capital,Population,GDP (2016),Capital Population,Longitude,Latitude
0,'Albania',2.874801e+04,'Tirana',2854710,1.186387e+10,49300,19.816667,41.316667
1,'Andorra',4.680112e+02,'Andorra_la_Vella',79034,2.858518e+09,22256,1.516667,42.500000
2,'Armenia',2.974300e+04,'Yerevan',2790974,1.057230e+10,1100000,44.500000,40.166667
3,'Austria',8.387802e+04,'Vienna',8922082,3.910000e+11,1900000,16.366667,48.200000
4,'Azerbaijan',6.960002e+03,'Baku',10312992,3.784772e+10,2240000,49.866667,40.383333
5,'Belarus',2.076001e+05,'Minsk',9578167,4.740722e+10,2000000,27.566667,53.900000
6,'Belgium',3.052800e+04,'Brussels',11611419,4.680000e+11,180000,4.333333,50.833333
7,'Bosnia and Herzegovina',5.120902e+04,'Sarajevo',3270943,1.691028e+10,280000,18.416667,43.866667
8,'Bulgaria',1.103720e+05,'Sofia',6885868,5.323788e+10,1280000,23.316667,42.683333
9,'Croatia',5.659403e+04,'Zagreb',4060135,5.071496e+10,900000,16.000000,45.800000
10,'Cyprus',9.251004e+03,'Nicosia',1244188,2.004701e+10,200000,33.366667,35.166667
11,'Czech Republic',7.887102e+04,'Prague',10510751,1.950000e+11,1360000,14.466667,50.083333
12,'Denmark',4.294701e+04,'Copenhagen',5854240,3.070000e+11,795000,12.583333,55.666667
13,'Estonia',4.539900e+04,'Tallinn',1328701,2.333791e+10,438000,24.716667,59.433333
14,'Faroe Islands',1.393000e+03,'Torshavn',52889,2.813000e+09,14000,-6.766667,62.000000
15,'Finland',3.368841e+05,'Helsinki',5535992,2.390000e+11,657000,24.933333,60.166667
16,'France',5.439412e+05,'Paris',64531444,2.470000e+12,2100000,2.333333,48.866667
17,'Georgia',3.040001e+03,'Tbilisi',3757980,1.437802e+10,1110000,44.833333,41.683333
18,'Germany',3.575811e+05,'Berlin',83408554,3.480000e+12,3800000,13.400000,52.516667
19,'Greece',1.319570e+05,'Athens',10445365,1.930000e+11,670000,23.733333,37.983333
20,'Hungary',9.302503e+04,'Budapest',9709786,1.260000e+11,1750000,19.083333,47.500000
21,'Iceland',1.030000e+05,'Reykjavik',370335,2.004741e+10,131000,-21.950000,64.150000
22,'Ireland',6.982502e+04,'Dublin',4986526,3.050000e+11,600000,-6.233333,53.316667
23,'Italy',3.019581e+05,'Rome',59240329,1.860000e+12,2860000,12.483333,41.900000
24,'Kosovo',1.091000e+04,'Pristina',1662009,6.649889e+09,150000,21.166667,42.666667
25,'Latvia',6.459401e+04,'Riga',1873919,2.757270e+10,628000,24.100000,56.950000
26,'Liechtenstein',1.600096e+02,'Vaduz',39039,6.237000e+09,6000,9.516667,47.133333
27,'Lithuania',6.528603e+04,'Vilnius',2786651,4.273888e+10,588000,25.316667,54.683333
28,'Luxembourg',2.586001e+03,'Luxembourg',639321,5.863132e+10,123000,6.116667,49.600000
29,'Malta',3.149946e+02,'Valetta',526748,1.099905e+10,6000,14.500000,35.883333
30,'Moldova',3.384700e+04,'Chisinau',3061506,6.749516e+09,535000,28.850000,47.000000
31,'Monaco',1.994292e+00,'Monaco',36686,6.473000e+09,40000,7.416667,43.733333
32,'Montenegro',1.388799e+04,'Podgorica',627859,4.374127e+09,156000,19.266667,42.433333
33,'Netherlands',4.154303e+04,'Amsterdam',17501696,7.770000e+11,875000,4.916667,52.350000
34,'North Macedonia',2.571301e+04,'Skopje',2103330,1.067000e+10,547000,21.433333,42.000000
35,'Norway',3.237721e+05,'Oslo',5403021,3.710000e+11,700000,10.750000,59.916667
36,'Poland',3.126791e+05,'Warsaw',38307726,4.710000e+11,1800000,21.000000,52.250000
37,'Portugal',9.142103e+04,'Lisbon',10290103,2.050000e+11,505000,-9.133333,38.716667
38,'Romania',2.382981e+05,'Bucharest',19328560,1.880000e+11,2150000,26.100000,44.433333
39,'Russia',3.952551e+06,'Moscow',146447424,1.280000e+12,12400000,37.600000,55.750000
40,'Serbia',7.758903e+04,'Belgrade',7296769,3.829985e+10,1700000,20.500000,44.833333
41,'Slovakia',4.903501e+04,'Bratislava',5447622,8.995000e+10,660000,17.116667,48.150000
42,'Slovenia',2.027302e+04,'Ljubljana',2119410,4.470860e+10,300000,14.516667,46.050000
43,'Spain',4.984852e+05,'Madrid',47486935,1.240000e+12,3300000,-3.683333,40.400000
44,'Sweden',4.385741e+05,'Stockholm',10467097,5.140000e+11,1500000,18.050000,59.333333
45,'Switzerland',4.129102e+04,'Bern',8691406,6.690000e+11,150000,7.466667,46.916667
46,'Turkey',2.375702e+04,'Ankara',84775404,8.640000e+11,1500000,32.866667,39.933333
47,'Ukraine',6.035492e+05,'Kiev',43531422,9.327048e+10,3000000,30.516667,50.433333
48,'United Kingdom',2.443761e+05,'London',67281039,2.650000e+12,9000000,-0.083333,51.500000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             49 non-null     object
 1   Area (km2)          49 non-null     float64
 2   Capital             49 non-null     object
 3   Population          49 non-null     int64
 4   GDP (2016)          49 non-null     float64
 5   Capital Population  49 non-null     int64
 6   Longitude           49 non-null     float64
 7   Latitude            49 non-null     float64
dtypes: float64(4), int64(2), object(2)
memory usage: 3.2+ KB

### 3. Load (Put the Data into a SQL Database)

### 3.1 Create a connection to MyQL

In [86]:
#Create a connection to MySQL through pymysql package

conn = pymysql.connect(database = 'EU_data', user = 'root', password = 'password')

In [87]:
cursor = conn.cursor()

### 3.2 Populate the data into the table in the database

In [88]:
insert_query = 'INSERT INTO eu_contries VALUES '

In [89]:
# Use a loop to cycle through dataframe columns and values and populate our MySQL table accordingly

# TODO - write the block of code to perform this
for i in range(df.shape[0]):
    insert_query +='('
    
    for j in range(df.shape[1]):
        insert_query +=str(df[df.columns.values[j]][i])+ ', '

    insert_query = insert_query[:-2]+'), '

In [90]:
# check the query now
insert_query

"INSERT INTO eu_contries VALUES ('Albania', 28748.008403399996, 'Tirana', 2854710, 11863865978.0, 49300, 19.816667, 41.31666667), ('Andorra', 468.01119299999993, 'Andorra_la_Vella', 79034, 2858517699.0, 22256, 1.516667, 42.5), ('Armenia', 29743.004861699996, 'Yerevan', 2790974, 10572298342.0, 1100000, 44.5, 40.16666667), ('Austria', 83878.0175454, 'Vienna', 8922082, 391000000000.0, 1900000, 16.366667, 48.2), ('Azerbaijan', 6960.002427299999, 'Baku', 10312992, 37847715736.0, 2240000, 49.866667, 40.38333333), ('Belarus', 207600.07865219997, 'Minsk', 9578167, 47407217531.0, 2000000, 27.566667, 53.9), ('Belgium', 30528.004930799998, 'Brussels', 11611419, 468000000000.0, 180000, 4.333333, 50.83333333), ('Bosnia and Herzegovina', 51209.023281, 'Sarajevo', 3270943, 16910277134.0, 280000, 18.416667, 43.86666667), ('Bulgaria', 110372.03535149999, 'Sofia', 6885868, 53237882473.0, 1280000, 23.316667, 42.68333333), ('Croatia', 56594.0268894, 'Zagreb', 4060135, 50714957391.0, 900000, 16.0, 45.8), ('Cyprus', 9251.0039817, 'Nicosia', 1244188, 20047013274.0, 200000, 33.366667, 35.16666667), ('Czech Republic', 78871.02297749999, 'Prague', 10510751, 195000000000.0, 1360000, 14.466667, 50.08333333), ('Denmark', 42947.00698079999, 'Copenhagen', 5854240, 307000000000.0, 795000, 12.583333, 55.66666667), ('Estonia', 45399.002313599995, 'Tallinn', 1328701, 23337907619.0, 438000, 24.716667, 59.43333333), ('Faroe Islands', 1393.0002216, 'Torshavn', 52889, 2813000000.0, 14000, -6.766667, 62.0), ('Finland', 336884.1173841, 'Helsinki', 5535992, 239000000000.0, 657000, 24.933333, 60.16666667), ('France', 543941.1787329, 'Paris', 64531444, 2470000000000.0, 2100000, 2.333333, 48.86666667), ('Georgia', 3040.0007625, 'Tbilisi', 3757980, 14378016729.0, 1110000, 44.833333, 41.68333333), ('Germany', 357581.11597259995, 'Berlin', 83408554, 3480000000000.0, 3800000, 13.4, 52.51666667), ('Greece', 131957.0379114, 'Athens', 10445365, 193000000000.0, 670000, 23.733333, 37.98333333), ('Hungary', 93025.03342859999, 'Budapest', 9709786, 126000000000.0, 1750000, 19.083333, 47.5), ('Iceland', 103000.0432149, 'Reykjavik', 370335, 20047413006.0, 131000, -21.95, 64.15), ('Ireland', 69825.0167043, 'Dublin', 4986526, 305000000000.0, 600000, -6.233333, 53.31666667), ('Italy', 301958.1022341, 'Rome', 59240329, 1860000000000.0, 2860000, 12.483333, 41.9), ('Kosovo', 10909.9961763, 'Pristina', 1662009, 6649888889.0, 150000, 21.166667, 42.66666667), ('Latvia', 64594.01390129999, 'Riga', 1873919, 27572698482.0, 628000, 24.1, 56.95), ('Liechtenstein', 160.00958219999998, 'Vaduz', 39039, 6237000000.0, 6000, 9.516667, 47.13333333), ('Lithuania', 65286.0333294, 'Vilnius', 2786651, 42738875963.0, 588000, 25.316667, 54.68333333), ('Luxembourg', 2586.0014154, 'Luxembourg', 639321, 58631324559.0, 123000, 6.116667, 49.6), ('Malta', 314.9945838, 'Valetta', 526748, 10999047580.0, 6000, 14.5, 35.88333333), ('Moldova', 33846.99941609999, 'Chisinau', 3061506, 6749515655.0, 535000, 28.85, 47.0), ('Monaco', 1.9942923, 'Monaco', 36686, 6473000000.0, 40000, 7.416667, 43.73333333), ('Montenegro', 13887.9925782, 'Podgorica', 627859, 4374127212.0, 156000, 19.266667, 42.43333333), ('Netherlands', 41543.025201599994, 'Amsterdam', 17501696, 777000000000.0, 875000, 4.916667, 52.35), ('North Macedonia', 25713.006321599998, 'Skopje', 2103330, 10670000000.0, 547000, 21.433333, 42.0), ('Norway', 323772.11170979997, 'Oslo', 5403021, 371000000000.0, 700000, 10.75, 59.91666667), ('Poland', 312679.10684009996, 'Warsaw', 38307726, 471000000000.0, 1800000, 21.0, 52.25), ('Portugal', 91421.0267217, 'Lisbon', 10290103, 205000000000.0, 505000, -9.133333, 38.71666667), ('Romania', 238298.06462669998, 'Bucharest', 19328560, 188000000000.0, 2150000, 26.1, 44.43333333), ('Russia', 3952551.2605254, 'Moscow', 146447424, 1280000000000.0, 12400000, 37.6, 55.75), ('Serbia', 77589.02972729999, 'Belgrade', 7296769, 38299854688.0, 1700000, 20.5, 44.83333333), ('Slovakia', 49035.01157489999, 'Bratislava', 5447622, 89950000000.0, 660000, 17.116667, 48.15), ('Slovenia', 20273.017225499996, 'Ljubljana', 2119410, 44708598649.0, 300000, 14.516667, 46.05), ('Spain', 498485.17073939997, 'Madrid', 47486935, 1240000000000.0, 3300000, -3.683333, 40.4), ('Sweden', 438574.1436569999, 'Stockholm', 10467097, 514000000000.0, 1500000, 18.05, 59.33333333), ('Switzerland', 41291.0191746, 'Bern', 8691406, 669000000000.0, 150000, 7.466667, 46.91666667), ('Turkey', 23757.019973699997, 'Ankara', 84775404, 864000000000.0, 1500000, 32.866667, 39.93333333), ('Ukraine', 603549.2028852, 'Kiev', 43531422, 93270479389.0, 3000000, 30.516667, 50.43333333), ('United Kingdom', 244376.07185939996, 'London', 67281039, 2650000000000.0, 9000000, -0.083333, 51.5), "

In [91]:
insert_query = insert_query[:-2] + ';'

In [92]:
# check the query once more
insert_query

"INSERT INTO eu_contries VALUES ('Albania', 28748.008403399996, 'Tirana', 2854710, 11863865978.0, 49300, 19.816667, 41.31666667), ('Andorra', 468.01119299999993, 'Andorra_la_Vella', 79034, 2858517699.0, 22256, 1.516667, 42.5), ('Armenia', 29743.004861699996, 'Yerevan', 2790974, 10572298342.0, 1100000, 44.5, 40.16666667), ('Austria', 83878.0175454, 'Vienna', 8922082, 391000000000.0, 1900000, 16.366667, 48.2), ('Azerbaijan', 6960.002427299999, 'Baku', 10312992, 37847715736.0, 2240000, 49.866667, 40.38333333), ('Belarus', 207600.07865219997, 'Minsk', 9578167, 47407217531.0, 2000000, 27.566667, 53.9), ('Belgium', 30528.004930799998, 'Brussels', 11611419, 468000000000.0, 180000, 4.333333, 50.83333333), ('Bosnia and Herzegovina', 51209.023281, 'Sarajevo', 3270943, 16910277134.0, 280000, 18.416667, 43.86666667), ('Bulgaria', 110372.03535149999, 'Sofia', 6885868, 53237882473.0, 1280000, 23.316667, 42.68333333), ('Croatia', 56594.0268894, 'Zagreb', 4060135, 50714957391.0, 900000, 16.0, 45.8), ('Cyprus', 9251.0039817, 'Nicosia', 1244188, 20047013274.0, 200000, 33.366667, 35.16666667), ('Czech Republic', 78871.02297749999, 'Prague', 10510751, 195000000000.0, 1360000, 14.466667, 50.08333333), ('Denmark', 42947.00698079999, 'Copenhagen', 5854240, 307000000000.0, 795000, 12.583333, 55.66666667), ('Estonia', 45399.002313599995, 'Tallinn', 1328701, 23337907619.0, 438000, 24.716667, 59.43333333), ('Faroe Islands', 1393.0002216, 'Torshavn', 52889, 2813000000.0, 14000, -6.766667, 62.0), ('Finland', 336884.1173841, 'Helsinki', 5535992, 239000000000.0, 657000, 24.933333, 60.16666667), ('France', 543941.1787329, 'Paris', 64531444, 2470000000000.0, 2100000, 2.333333, 48.86666667), ('Georgia', 3040.0007625, 'Tbilisi', 3757980, 14378016729.0, 1110000, 44.833333, 41.68333333), ('Germany', 357581.11597259995, 'Berlin', 83408554, 3480000000000.0, 3800000, 13.4, 52.51666667), ('Greece', 131957.0379114, 'Athens', 10445365, 193000000000.0, 670000, 23.733333, 37.98333333), ('Hungary', 93025.03342859999, 'Budapest', 9709786, 126000000000.0, 1750000, 19.083333, 47.5), ('Iceland', 103000.0432149, 'Reykjavik', 370335, 20047413006.0, 131000, -21.95, 64.15), ('Ireland', 69825.0167043, 'Dublin', 4986526, 305000000000.0, 600000, -6.233333, 53.31666667), ('Italy', 301958.1022341, 'Rome', 59240329, 1860000000000.0, 2860000, 12.483333, 41.9), ('Kosovo', 10909.9961763, 'Pristina', 1662009, 6649888889.0, 150000, 21.166667, 42.66666667), ('Latvia', 64594.01390129999, 'Riga', 1873919, 27572698482.0, 628000, 24.1, 56.95), ('Liechtenstein', 160.00958219999998, 'Vaduz', 39039, 6237000000.0, 6000, 9.516667, 47.13333333), ('Lithuania', 65286.0333294, 'Vilnius', 2786651, 42738875963.0, 588000, 25.316667, 54.68333333), ('Luxembourg', 2586.0014154, 'Luxembourg', 639321, 58631324559.0, 123000, 6.116667, 49.6), ('Malta', 314.9945838, 'Valetta', 526748, 10999047580.0, 6000, 14.5, 35.88333333), ('Moldova', 33846.99941609999, 'Chisinau', 3061506, 6749515655.0, 535000, 28.85, 47.0), ('Monaco', 1.9942923, 'Monaco', 36686, 6473000000.0, 40000, 7.416667, 43.73333333), ('Montenegro', 13887.9925782, 'Podgorica', 627859, 4374127212.0, 156000, 19.266667, 42.43333333), ('Netherlands', 41543.025201599994, 'Amsterdam', 17501696, 777000000000.0, 875000, 4.916667, 52.35), ('North Macedonia', 25713.006321599998, 'Skopje', 2103330, 10670000000.0, 547000, 21.433333, 42.0), ('Norway', 323772.11170979997, 'Oslo', 5403021, 371000000000.0, 700000, 10.75, 59.91666667), ('Poland', 312679.10684009996, 'Warsaw', 38307726, 471000000000.0, 1800000, 21.0, 52.25), ('Portugal', 91421.0267217, 'Lisbon', 10290103, 205000000000.0, 505000, -9.133333, 38.71666667), ('Romania', 238298.06462669998, 'Bucharest', 19328560, 188000000000.0, 2150000, 26.1, 44.43333333), ('Russia', 3952551.2605254, 'Moscow', 146447424, 1280000000000.0, 12400000, 37.6, 55.75), ('Serbia', 77589.02972729999, 'Belgrade', 7296769, 38299854688.0, 1700000, 20.5, 44.83333333), ('Slovakia', 49035.01157489999, 'Bratislava', 5447622, 89950000000.0, 660000, 17.116667, 48.15), ('Slovenia', 20273.017225499996, 'Ljubljana', 2119410, 44708598649.0, 300000, 14.516667, 46.05), ('Spain', 498485.17073939997, 'Madrid', 47486935, 1240000000000.0, 3300000, -3.683333, 40.4), ('Sweden', 438574.1436569999, 'Stockholm', 10467097, 514000000000.0, 1500000, 18.05, 59.33333333), ('Switzerland', 41291.0191746, 'Bern', 8691406, 669000000000.0, 150000, 7.466667, 46.91666667), ('Turkey', 23757.019973699997, 'Ankara', 84775404, 864000000000.0, 1500000, 32.866667, 39.93333333), ('Ukraine', 603549.2028852, 'Kiev', 43531422, 93270479389.0, 3000000, 30.516667, 50.43333333), ('United Kingdom', 244376.07185939996, 'London', 67281039, 2650000000000.0, 9000000, -0.083333, 51.5);"

### 3.3 Execute the query

In [93]:
# Now execute the query
cursor.execute(insert_query)

49

In [94]:
# Commit the changes to SQL connection
conn.commit()

In [95]:
conn.close()

### Part 2: Run queries against an existing database table

We will use the employees schema for this practical. Download the file employees.sql from blackboard. It consists of tables: employees, titles, salaries, departments, dept_manager.

In [ ]:
#Create a connection to MySQL through pymysql package

conn = pymysql.connect(database = 'employees', user = 'root', password = 'password')

In [ ]:
cursor = conn.cursor()

#### TOPIC: Select, JOIN, COUNT, AVG

**Q1:** Return employee number, first name, last name and hire date of all employees with the first name Vincent (hint: WHERE).

In [ ]:
# Question 1

cursor.execute('SELECT fisrt_name, last_name, hire_data FROM employees WHERE first_name ="Vincent";')

In [ ]:
results = cursor.fetchall()
for row in results:
    print(row)

**Q2:** Return all columns for all employees whose first name starts with “Mar..” i.e. Mark, Margaret, Markus etc. (hint: LIKE and “Letters%”).

In [ ]:
# Question 2

#TODO:

**Q3:** Number of employees with the last name Boyle (hint: COUNT, WHERE).

In [ ]:
# Question 3

#TODO:

**Q4:** Get the top 10 last names within the company (hint: GROUP BY, ORDER BY, LIMIT).

In [ ]:
# Question 4

#TODO:

**Q5:** How many employees were hired by the company in the whole of the year 1985? (Hint: COUNT, BETWEEN).

In [ ]:
# Question 5

#TODO:

**Q6:** Find the average salary per job title. (Hint: JOIN, GROUP BY).

In [ ]:
# Question 6

#TODO:

#### TOPIC: Nested / Subqueries

**Q7:** Using a subquery, find the first name, last name and salary of the employee with the highest salary (still at company).

In [ ]:
# Question 7

#TODO:

**Q8:** Find the first name, last name, and job-titles of all employees with the same job-title as Georgi Facello using a sub-query in the WHERE clause of the main outer query. Hint: First find the job-title of Georgi Facello using a query, and then put that query into the WHERE clause of the main query (Hence it will act as the inner query).

Note: you’ll need to make use of JOIN and a WHERE condition within that inner query including to_date = ‘9999-01-01’. You’ll also need to use a JOIN in the outer query too.

In [ ]:
# Question 8

#TODO:

Finally close the connection

In [ ]:
conn.close()